'use strict';

/**
 * Mascara tierra/oceano del planeta a resolucion 440x280 (proyeccion
 * equirectangular: columna = longitud -180..180, fila = latitud 90..-90),
 * horneada UNA VEZ a partir de datos publicos de costas (Natural Earth,
 * capa "land" a 110m, dominio publico -- no requiere atribucion ni tiene
 * copyright, ver https://www.naturalearthdata.com/about/terms-of-use/).
 *
 * No hay ninguna libreria de imagenes/geometria en tiempo de ejecucion: esto
 * es sencillamente 1 bit por celda de raster (1 = tierra, 0 = oceano), fila
 * por fila, empaquetado en base64. server/mapTemplates.js la usa para que el
 * reparto en `tileCount` territorios (ver generateMap()) ocurra solo sobre
 * tierra -- el oceano nunca se divide ni tiene dueno. Si se quiere cambiar la
 * resolucion del raster hay que regenerar esta mascara (ver README para el
 * script de generacion), no se puede reescalar a mano.
 */

const COLS = 440;
const ROWS = 280;

const LAND_MASK_BASE64 =
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//8AAAA///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAB////+AAj/////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////9////////wPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////8//////////8AAAAAAAAAAAA' +
  'AAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////////gAAAAAAH8AAAP+AAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////z//////////wAAAAAL//wAAA8AAAAAAAAf/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAP////gH///' +
  '//////gAAAAA/+/wAAAAAAAAAAAAA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPB+cf///P//////////wAAAAAH//AAAAAAAAAAAAAAD/+AAAAAAAAAAAAAAAAAAAAAAAAAAAADwf77///j//////////8AAAAAAP5+AAAAAAAAAAAAAAB/gAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAADx8AAfA//gH//////////AAAAAAD8cAAAAAAAAAAAAAAAD8AAAAAAAAAAAAAAAAAAAAAAAAAAH8AwB3+//4D//////////8AAAAAAGAAAAAAAAAD4AAAAAB/vAAAAAAAAAAAAAAAAAAAAAAAAAH9+9j+///wAP/////////8AAAAAAAAAAAAAAAA/8AAAAH///+' +
  'AAAAD4AAAAAAAAAAAAAAAAAAAA//4/v//+AAAA////////gAAAAAAAAAAAAAAD/wAAAAP////wAAAB//wAAAAAAAAAAAAAAAAAAH/+D/3//gAAAP///////gAAAAAAAAAAAAAAH8AAAAA/////wAAAAH+/gAAAAAAAAAAAAAAAAf+OAAAPP/AAAAA///////+AAAAAAA' +
  'AAAAAAAB8AAAAAf////yAAAAAAAAAAAAAAAAAAAAAAAAD/8Aef/9/3gAAAH///////AAAAAAAAAAAAAAB8AAAAP///////w/AAPwAAAAAAAAAAAAAAAAAB//5fP78+/+AAAA//////8AAAAAAAAAAAAAAA+AAPkD/////////8ABcAAAAAAAAAAAAAAAAAA///7z/4f/' +
  '/wAAAH//////gAAAAAAAAAAAAAA/AAD5v//////////AA//gAAAAAMAAAAgAAAAAP7//8H3D///QAAH//////4AAAAAAAAAAAAAAHwAB9///////////x8//8AAAAADgAAB/wAAAAAwf//gz4///+AAAf/////+AAAAAAAAAPgAAAAfgB/v////////////////+AAAD' +
  'AAAD///IAAWQH//+E/n///+AAH//////wAAAAAAAA//gAAAAQAf7/////////////////wAIAAAAD////8H/9w///5/8H+//wAB//////gAAAAAAAB//8AAAAAfH////////////////////3+CAAP////////////8//h+D/+AAN/////wAAAAAAAA///+AAAYT8fv/' +
  '/////////////////+//4AD////////////yHv+fg/8AAB/////gAAAAAAAA////4Hgd//z///////////////////////gAf//////////8////v4e/+AAf///+AAAAAAAAA/////w//////f//////////////////////wB////////////////+Hn/+AP///4AAA' +
  'AAAAAAf////+c/////v//////////////////////+A3///////////////+AH//gD///+ABiOAAAAAP/////7/////3///////////////////////7////////////////8AB/n4A///8AA//AAAAAH////iP///////////////////////////+/8P//////////' +
  '/////9wP/+wAD//wAAD/8AAAAD/8P/5P////////////////////////////D8D/////////////////n//4AA//4AAD/8AAAAD//j/+/////////////////////////////gGwAf//////////////P+Q/+AAP/+AAAP4AAAAB//3/////////////////////////' +
  '//////wAPD///////////////HxAH/gAD//AAAAEAAAAA//7///////////////////////////////+AAg///////////////wHJEf4AAH/AAAAAAAAAB//x////////////////////////////////wAAf//////////////gBn/h8AAB/4AAAAAAAAA//4P/////' +
  '///////////////////////n/8EAAP//////////////wAAv+AAAAf8AAAAAAAAAP/+D///////////////////////////x7/+AAAB//////////////4AAD/4AAAB+AAAAAAAAAD//w///////////////////////////4R/+AAAB////D/////////+AAAf+DAAA' +
  'BgAAAAAAAAA//+H5/////////////////////////8B/CAAAAIf/OAH/////////gAAH/g4AAAAAAAAAAAAAP//A///////////////////////////B9AAAAAAD/4AAH////////+AAD/+eAAAAAAAAAAAHgD9/wP///////////////////////8AOA+AAAAAAAF/A' +
  'AAf////////gAAf//wAAAAAAAAAABwAOP4B///////////////////////+AAAfgAAAAAAA/4AAA////////6AAD//8AAAAAAAAAAA/AAb+Df//////////////////////+AAAf8AAAAAAAOYAAAP////////8AA///gAAAAAAAAAAPwAOfh///////////////////' +
  '/////AAAP/AAAAAAAeAAAAA/////////wAP//4AAAAAAAAAAB4AH3wf///////////////////////gAAD/wAAAAAA+AAAAAP/////////gH///gAAAAAAAAAAfAB3wH///////////////////////gAAB/wAAAAAAcAAAAAB//////////P////AAAAAAAAAB3wAOg' +
  'b///////////////////////wAAAf+AAAAAAIAAAAABv/////////x////wAAAAAAAAAffAD+/////////////////////////ZgAD+AAAAAAAAAAAAAZ/////////8f////AAAAAAAAAPvwH///////////////////////////IAA/AAAAAAAAAAAAAGP/////////' +
  'H////wAAAAAAAAD7/n////////////////////////////AAPwAAAAAAAAAAAAAx/////////5////8AAAAAAAAA8/x////////////////////////////wABwAAAAAAAAAAAAAAf/////////f////gAAAAAAAAcf8////////////////////////////cAAcAAAA' +
  'AAAAAAAAAAD//////////////4AAAAAAAAAD/////////////////////////////3AAEAAAAAAAAAAAAAAB/////////////+cAAAAAAAAAD/v///////////////////////////9wAAAAAAAAAAAAAAAAAf///////////8eHwAAAAAAAAARH////////////////' +
  '////////////cAAAAAAAAAAAAAAAAAA///////////+7j+AAAAAAAAABP////////////////////////////3gAAAAAAAAAAAAAAAAAP////////////B/wAAAAAAAAA/////////////////////////////9gAAAAAAAAAAAAAAAAAB////////////gf8AAAAAAA' +
  'AAP////////////////////////////+YAAAAAAAAAAAAAAAAAAP///////////8ILAAAAAAAAAA///////////f/////////////////GAAAAAAAAAAAAAAAAAAD////////////+HwAAAAAAAAAD///////7//B/////////////////hwAAAAAAAAAAAAAAAAAA//' +
  '///////////gAAAAAAAAAAA//////84//gP////////////////wUAAAAAAAAAAAAAAAAAAP////////////wAAAAAAAAAAAP/////+f//wH////////////////8EAAAAAAAAAAAAAAAAAAD////////////gAAAAAAAAAAAD//9///D3/4H////////////////+Bk' +
  'AAAAAAAAAAAAAAAAAA///////////5wAAAAAAAAAACA///P//gAf/B/////////////////AfAAAAAAAAAAAAAAAAAAP//////////4YAAAAAAAAAAB///z5//4AD/wf////////////////gfwAAAAAAAAAAAAAAAAAH//////////8AAAAAAAAAAAA//8D/H/8AAf8' +
  'B///////////////+wP4AAAAAAAAAAAAAAAAAA///////////gAAAAAAAAAAAP//A38f/g4D/gP///////////////ABkAAAAAAAAAAAAAAAAAAP//////////4AAAAAAAAAAAB//gM/n/8fw/8B///////////////gAYAAAAAAAAAAAAAAAAAAD//////////4AAAA' +
  'AAAAAAAAf/gHB9//////Af//////////////4AOAAAAAAAAAAAAAAAAAAB//////////wAAAAAAAAAAAAH/4AwP/z////wP////////////+f8ABwAAAAAAAAAAAAAAAAAAP/////////8AAAAAAAAAAAAD/8AMBrx////8H/////////////O8AAcAAAAAAAAAAAAAA' +
  'AAAAD/////////+AAAAAAAAAAAAA//gDAYeP///+A/////////////nPgAHAAAAAAAAAAAAAAAAAAAf/////////gAAAAAAAAAAAAP/wAB8Hz////gP////////////4D4ADgAAAAAAAAAAAAAAAAAAD/////////wAAAAAAAAAAAAB/8AEfA8f///8D////////////' +
  '/cfAF4AAAAAAAAAAAAAAAAAAAf////////8AAAAAAAAAAAAAf8H/zgMH////w//////////////D4D+AAAAAAAAAAAAAAAAAAAH/////////AAAAAAAAAAAAAAwP/4IBgN3/////////////////A+A/AAAAAAAAAAAAAAAAAAAA/////////wAAAAAAAAAAAAANP//A' +
  'AOAP/////////////////gPj/4AAAAAAAAAAAAAAAAAAAP////////4AAAAAAAAAAAAAD///wAD4Hf////////////////wDx/8AAAAAAAAAAAAAAAAAAAD////////8AAAAAAAAAAAAAB///4AAABn////////////////+Ax/8AAAAAAAAAAAAAAAAAAAAH///////' +
  '+AAAAAAAAAAAAAA////AAAAB/////////////////gAfwAAAAAAAAAAAAAAAAAAAAA////////AAAAAAAAAAAAAAf///8AIAA/////////////////8APoAAAAAAAAAAAAAAAAAAAAAP///////AAAAAAAAAAAAAAP////4PgAP/////////////////gD4AAAAAAAAA' +
  'AAAAAAAAAAAAB///////wAAAAAAAAAAAAAD////+D/hD/////////////////4AYAAAAAAAAAAAAAAAAAAAAAAd//////4AAAAAAAAAAAAAA/////4////////////////////+AGAAAAAAAAAAAAAAAAAAAAAAHf/////+AAAAAAAAAAAAAAP//////////////////' +
  '////////gAAAAAAAAAAAAAAAAAAAAAAAA7////4fgAAAAAAAAAAAAAD//////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAP///+uA8AAAAAAAAAAAAAB///////////+P//////////////AAAAAAAAAAAAAAAAAAAAAAAAA3///AAPAAAAAAAAAAAAA' +
  'A////////////z//////////////gAAAAAAAAAAAAAAAAAAAAAAAAe///AADwAAAAAAAAAAAAA////////////8//////////////4AAAAAAAAAAAAAAAAAAAAAAAADn//gAA8gAAAAAAAAAAAAf////////+f//j/////////////8AAAAAAAAAAAAAAAAAAAAAAAAA' +
  '9//4AAH8AAAAAAAAAAAAH/////////z//8f////////////+AAAAAAAAAAAAAAAAAAAAAAAAADP//AAA5AAAAAAAAAAAAD/////////8///w/////////////gAAAAAAAAAAAAAAAAAAAAAAAAA7//gAAMgAAAAAAAAAAAB//////////n//8Z////////////yAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAOP/4AAAIAAAAAAAAAAAAf/////////5//+OAA//////////9wAAAAAAAAAAAAAAAAAAAAAAAAAx/+AAADAAAAAAAAAAAAH//////////f///4AP/////////+YAAAAAAAAAAAAAAAAAAAAAAAAAGf/gAAQwAAAAAAAAAAAD//////////x//' +
  '//AB//////////OAAAAAAAAAAAAAAAAAAAAAAAAABD/4AAfoAAAAAAAAAAAA//////////8f///8AP/////////DgAAAAAAAAAAAAAAAwAAAAAAAAAA/+AAN+AAAAAAAAAAAAf//////////3////AD////v////AQAAAAAAAAAAAAAAADAAAAAAAAAAH/gDyH4AAAAA' +
  'AAAAAAH//////////9////gAf///7///+AAAAAAAAAAAAAAAAAAcAAAAAAAAAB/8B8APgAAAAAAAAAAB///////////P///wACf//g///mAAAAAAAAAAAAAAAAAABgAAAAAAAAA//AfAB8AAAAAAAAAAAf//////////z///8AAH//wH//wwAAAAAAAAAAAAAAAAAAYA' +
  'AAAAAAAAH/4HwAm/AAAAAAAAAAH//////////8P//+AAB//wB//88AAAAAAAAAAAAAAAAAAGAAAAAAAAAA/+H4AAXwAAAAAAAAAA///////////D///gAAf/4AH//PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//+ADv/wAAAAAAAAAP//////////4f//wAAH/+AB//7A' +
  'AcAAAAAAAAAAAAAAAAAAAAAAAAAAA///gA4IcAAAAAAAAAD//////////+H//4AAB//AAf/+AAHAAAAAAAAAAAAAAAAAAAAAAAAAAAD//4AAAAAAAAAAAAAA///////////x//8AAAf/gAH//wABwAAAAAAAAAAAAAAAAAAAAAAAAAAAP/+AAAAAAAAAAAAAAf//////' +
  '////8P/8AAAH/4AB3/+AA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAZ//AAAAAAAAAAAAAH///////////j/8AAAB/4AAZ//gAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/4AAAAAAAAAAAAD///////////8/+AAAAP8AAAf/8ADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/+' +
  'AAAAAAAAAAAAA////////////v+AAAAD/AAAH//AAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/gAAAAAAAAAAAAH/////////////AAAAAf4AAB//wAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAAAAAAAAAB/////////////AAAAAH+AAAP/8AB8AAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAB8AAgAAAAAAAAAAf///////////+AAAAAB/AAAD//AAZwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfAAeAAAAAAAAAAH///////////+A4AAAAPwAAA5/wADsAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwA/wAAAAAAAAAA////////////w+AAAAD8' +
  'AAAMf4ACfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+Af/3wAAAAAAAAH/////////////gAAAAfAAADD8ABnwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgH//8AAAAAAAAA/////////////4AAAAHwAAAwOAAx8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/5///AAAAAAAAA' +
  'H////////////8AAAAB+AAAODgAYJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////4AAAAAAAAB/////////////AAAAAdwAADggAEC4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+////AAAAAAAAAf////////////wAAAADcAAB4AAAB+AAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAADv///4AAAAAAAAD////////////4AAAAAHAAAGAAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////AAAAAAAAAf///////////+AAAAABwAAB4AAMF4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///+AAAAAAAAD////////////AAAAAAMAAAPAADAeAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAH////8AAAAAAAAf/wP////////wAAAAAAAADzwAB8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////gAAAAAAAD54D////////4AAAAAAAAA8+AB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////8AAAAAAAAIAAf///////+' +
  'AAAAAAAAAHngA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////AAAAAAAAAAAAf///////AAAAAAAAAA94APwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////wAAAAAAAAAAAH///////gAAAAAAAAAHeAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////+' +
  'AAAAAAAAAAAB///////wAAAAAAAAAB/gL/gAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////gAAAAAAAAAAAf//////4AAAAAAAAAAP8H/5DcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////4AAAAAAAAAAAH//////8AAAAAAAAAAD+B//fnAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAD/////+AAAAAAAAAAAB//////+AAAAAAAAAAAfgf/P4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//////8AAAAAAAAAAAf//////AAAAAAAAAAAD4H/yIIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////wAAAAAAAAAAP//////wAAAAAAAAAAA/B/' +
  '9uCfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///////AAAAAAAAAAB//////8AAAAAAAAAAAHwf+fADxwAAAAAAAAAAAAAAAAAAAAAAAAAAAB///////4AAAAAAAAAAf/////8AAAAAAAAAAAB/D/ngAe/AAgAAAAAAAAAAAAAAAAAAAAAAAAAf///////8AAAAAAAAAD/' +
  '/////AAAAAAAAAAAAfw/58f3v4AMAAAAAAAAAAAAAAAAAAAAAAAAAH////////gAAAAAAAAAf/////wAAAAAAAAAAAD8CcfD8//gBgAAAAAAAAAAAAAAAAAAAAAAAAD////////8AAAAAAAAAH/////4AAAAAAAAAAAAfADDwBN//AcAAAAAAAAAAAAAAAAAAAAAAAAA' +
  '/////////wAAAAAAAAA/////8AAAAAAAAAAAADwAA+AAP/4ewAAAAAAAAAAAAAAAAAAAAAAAAH////////+AAAAAAAAAP/////AAAAAAAAAAAAAcAAdgAI/+fEAAAAAAAAAAAAAAAAAAAAAAAAD/////////gAAAAAAAAD/////wAAAAAAAAAAAAH4AAAAGH//hgAAAA' +
  'AAAAAAAAAAAAAAAAAAAAf////////8AAAAAAAAAf////+AAAAAAAAAAAAA/8AAAAh/+AeAAAAAAAAAAAAAAAAAAAAAAAAD/////////AAAAAAAAAH/////gAAAAAAAAAAAAD/gAAAA//AB4AAAAAAAAAAAAAAAAAAAAAAAA/////////wAAAAAAAAA/////wAAAAAAAA' +
  'AAAAAP8NIQAP84AHgAAAAAAAAAAAAAAAAAAAAAAAH////////8AAAAAAAAAf////8AAAAAAAAAAAAAAE3+8ADPGAAYAAAAAAAAAAAAAAAAAAAAAAAB////////+AAAAAAAAAH/////gAAAAAAAAAAAAAADYcAADh4AHAAAAAAAAAAAAAAAAAAAAAAAAP////////gAAA' +
  'AAAAAA/////4AAAAAAAAAAAAAAABOAAAAPABwAAAAAAAAAAAAAAAAAAAAAAAD////////wAAAAAAAAAP/////AAAAAAAAAAAAAAAABAAACAYAGAAAAAAAAAAAAAAAAAAAAAAAA////////4AAAAAAAAAD/////wAAAAAAAAAAAAAAAAABgBgAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAH///////8AAAAAAAAAA/////8AIAAAAAAAAAAAAAAAAugYAAAAAAAAAAAAAAAAAAAAAAAAAAAB////////AAAAAAAAAAP/////AGAAAAAAAAAAAAAAAAf8HAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////wAAAAAAAAAH/////wBgAAAAAAAAAAAAAAAH/Bw' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAD///////4AAAAAAAAAB/////8A8AAAAAAAAAAAAAAAz/g8AAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////+AAAAAAAAAA//////APAAAAAAAAAAAAAAA+/wHwAAAEAAAAAAAAAAAAAAAAAAAAAAAD///////gAAAAAAAAAP/////wH' +
  'wAAAAAAAAAAAAAAP/8B8AAABgACAAAAAAAAAAAAAAAAAAAAAf//////4AAAAAAAAAD/////4H8AAAAAAAAAAAAAAD//w/AAAAYAAgAAAAAAAAAAAAAAAAAAAAD//////+AAAAAAAAAA/////+D+AAAAAAAAAAAAAAD//+PwAAADAAwAAAAAAAAAAAAAAAAAAAAAf////' +
  '//gAAAAAAAAAP/////g/gAAAAAAAAAAAAAB///7+AAAAAAMAAAAAAAAAAAAAAAAAAAAAD//////4AAAAAAAAAD/////Af4AAAAAAAAAAAAAAf////gAAAAAOAAAAAAAAAAAAAAAAAAAAAAf/////8AAAAAAAAAA/////gH8AAAAAAAAAAAAAAH////4AAAAADgAAAAAA' +
  'AAAAAAAAAAAAAAAD//////AAAAAAAAAAH////4A/AAAAAAAAAAAAAAD////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////wAAAAAAAAAB////8APwAAAAAAAAAAAAAB/////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////4AAAAAAAAAAP///+AD8AAAAAAAAAAAAA' +
  'D//////AAAwAAAAAAAAAAAAAAAAAAAAAAAAD/////+AAAAAAAAAAD////gB/AAAAAAAAAAAAAH//////wAAGAAAAAAAAAAAAAAAAAAAAAAAAA//////AAAAAAAAAAA////8AfgAAAAAAAAAAAAH//////+AAAwAAAAAAAAAAAAAAAAAAAAAAAAP/////wAAAAAAAAAAH' +
  '////AP4AAAAAAAAAAAAB///////4AAGAAAAAAAAAAAAAAAAAAAAAAAAH/////4AAAAAAAAAAB////wD+AAAAAAAAAAAAAf//////+AAAAAAAAAAAAAAAAAAAAAAAAAAAB/////wAAAAAAAAAAAf///8AfgAAAAAAAAAAAAP///////gAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAf////4AAAAAAAAAAAH////AHwAAAAAAAAAAAAD///////8AAAAAAAAAAAAAAAAAAAAAAAAAAAH////wAAAAAAAAAAAA////gB8AAAAAAAAAAAAA////////AAAAAAAAAAAAAAAAAAAAAAAAAAAB////4AAAAAAAAAAAAP///gAOAAAAAAAAAAAAAP///////4AAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAf///+AAAAAAAAAAAAD///4AAAAAAAAAAAAAAAD////////AAAAAAAAAAAAAAAAAAAAAAAAAAAH////gAAAAAAAAAAAA///+AAAAAAAAAAAAAAAA////////wAAAAAAAAAAAAAAAAAAAAAAAAAAB////4AAAAAAAAAAAAP///AAAAAAAAAA' +
  'AAAAAAH///////8AAAAAAAAAAAAAAAAAAAAAAAAAAAf///+AAAAAAAAAAAAB///wAAAAAAAAAAAAAAAB////////AAAAAAAAAAAAAAAAAAAAAAAAAAAP////gAAAAAAAAAAAAf//8AAAAAAAAAAAAAAAAP///////wAAAAAAAAAAAAAAAAAAAAAAAAAAD////wAAAAAA' +
  'AAAAAAD//+AAAAAAAAAAAAAAAAD///////8AAAAAAAAAAAAAAAAAAAAAAAAAAA////8AAAAAAAAAAAAA///AAAAAAAAAAAAAAAAA////////AAAAAAAAAAAAAAAAAAAAAAAAAAAP///+AAAAAAAAAAAAAH//wAAAAAAAAAAAAAAAAP///////wAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAD////gAAAAAAAAAAAAA//4AAAAAAAAAAAAAAAAB///////8AAAAAAAAAAAAAAAAAAAAAAAAAAA////gAAAAAAAAAAAAAP/8AAAAAAAAAAAAAAAAAf//n///+AAAAAAAAAAAAAAAAAAAAAAAAAAAP///4AAAAAAAAAAAAAH//AAAAAAAAAAAAAAAAAH//AP//' +
  '/gAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAA//AAAAAAAAAAAAAAAAAB/8AH///wAAAAAAAAAAAAAAAAAAAAAAAAAAA///+AAAAAAAAAAAAAAP/gAAAAAAAAAAAAAAAAA//AAf//4AAAAAAAAAAAAAAAAAAAAAAAAAAAP///gAAAAAAAAAAAAAD4AAAAA' +
  'AAAAAAAAAAAAAPwAAH//+AAAAwAAAAAAAAAAAAAAAAAAAAAAH///gAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAA4AAA///gAAAHAAAAAAAAAAAAAAAAAAAAAAB///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAwAAAAAAAAAAAAAAAAAAAAAAf//4A' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/8AAAAOAAAAAAAAAAAAAAAAAAAAAAP//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//AAAABgAAAAAAAAAAAAAAAAAAAAAD///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/wAAAAfgAAAAAA' +
  'AAAAAAAAAAAAAAA///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/gAAAAHwAAAAAAAAAAAAAAAAAAAAAP//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAAAD8AAAAAAAAAAAAAAAAAAAAAD//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAA+AAAAAAAAAAAAAAAAAAAAAB//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXgAAAAAAAAAAAAAAAAAAAAAf/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAAOwAAAAAAAAAAAAAAAAAAAAAH/6AAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAH8AAAAAAAAAAAAAAAAAAAAAB//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAB4AAAAAAAAAAAAAAAAAAAAAAX/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAA8AAAAAAAAAAAAAAAAAAAAA' +
  'AF/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAfAAAAAAAAAAAAAAAAAAAAAAB/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAf/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwA' +
  'AAAAAAAAAAAAAAAAAAAAAP/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAD/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+AAAAAAAAAAAAAAAAAAAAAAB/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAH/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/8AAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/wAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAA/4BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAD0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+AAAAAAAAAAAAAAAAAAAAAAA+AAAAA' +
  'AQAAcA8AAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAAAAAAAA/wAAAAAEAAfh/4H//4PgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAAAAAAAAAAAAAAAAAAAAAB//wgAAD////////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAA' +
  'AAAAAAAAAAAAP////4AH/////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAGAf////+AH//////////////8gAAAAAAAAAAAAAAAAAAAAAAAAAAG/gAAAAAAAAAAAAAAAAAAD8//////wB////////////////AAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAD/8AAAAAAAAAAAAABQ/+AP///////8P/////////////////AAAAAAAAAAAAAAAAAAAAAAAAAA//AAAAAAAAAAAAAD+///////////+H/////////////////8AAAAAAAAAAAAAAAAAAAAAAAAB//4AAAAAAAAABuPf/////////////n///////////////' +
  '////8AAAAAAAAAAAAAAAAAP0AAAA//+AAAAAAAAAA////////////////x////////////////////wAAAAAAAAAAAAAAAAF/gIAAP9/wAAAAAAAAA/////////////////////////////////////8AAAAAAAAAAAAQAAAB/hz4EAP/8AAAAAAAAB/////////////' +
  '////////////////////////8AAAAAAAAAAAAPvggAf////+///AAAAAAAAB/////////////////////////////////////+AAAAAAAAAAB////8gD////////gAAAAAAAAP////////////////////////////////////+AAAAAAAAAI////////3///////gAA' +
  'AAAAAAP////////////////////////////////////+AAAAAAAAAP////////////////wAAAAAAAAf////////////////////////////////////+AAAAAAAAAB///////////////+AAAAAAAA///////////////////////////////////////gAAAAAADCD' +
  '///////////////8AAAAAAAB///////////////////////////////////////wAAAAAAA/////////////////wAAAAAAAD///////////////////////////////////////+AAAAAAOP////////////////8AAAAD4AP//////////////////////////////' +
  '//////////8AAAAAH8f///////////////gAAAAD/gD/////////////////////////////////////////gAAAAAfA///////////////+AABAB/4A////////////////////////////////////////+AAAAAAAAAD//////////////wA8cD//AAD/////////' +
  '/////////////////////////////4AAAAAAAAAA///////////////4H+B/8AB///////////////////////////////////////8AAAAAAAAP//////////////////AgAgA/////////////////////////////////////////gAAAAAAAAf//////////////' +
  '////gD///////////////////////////////////////////+AAAAAAAAD///////////////////v////////////////////////////////////////////8AAAAAAAA/////////////////////////////////////////////////////////////////+AA' +
  'TPwAAP/////////////////////////////////////////////////////////////////+EP//8AAP////////////////////////////////////////////////////////////////////////8H//////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////w==';

/** Decodifica la mascara a un Uint8Array de COLS*ROWS (1 = tierra, 0 = oceano), indexado fila por fila. */
function decodeLandMask() {
  const buf = Buffer.from(LAND_MASK_BASE64, 'base64');
  const mask = new Uint8Array(COLS * ROWS);
  for (let i = 0; i < COLS * ROWS; i++) {
    const byteIndex = i >> 3;
    const bitIndex = 7 - (i & 7);
    mask[i] = (buf[byteIndex] >> bitIndex) & 1;
  }
  return mask;
}

module.exports = { decodeLandMask, COLS, ROWS };
